### ISSUE TITLE
segformer preprocessing problems 

### ISSUE THREAD

**Issue by concrete13377** [hukenovs/easyportrait#19]
```python easyportrait\pipelines\demo\image_demo.py "images\2.jpg" "easyportrait\pipelines\local_configs\easyportrait_experiments_v2\segformer-fp\segformer-fp.py" "easyportrait\ckpt\faceparse_segformer-fp-512.pth" --palette=easy_portrait --out-file="result.png"```

I got the following error:
```img_meta[key] = results[key]
KeyError: 'pad_shape'```

torch==2.1.1
mmcv-full==1.7.1
mmsegmentation==0.30.0
mmcls==0.25.0

I dont have your torch version, but the problem does not seems to be in torch, looks like the config is wrong

**Comment by concrete13377** [comment]
the only thing that helped is to replace [this](https://github.com/hukenovs/easyportrait/blob/4127bdfa56e349df495633e989da2e16edd1ab42/pipelines/mmseg/datasets/pipelines/formatting.py#L281C1-L282C1) line with ```img_meta[key] = results.get(key, None)```

**Comment by concrete13377** [comment]
very results with segformer-1024 model, thanks for your work :)

**Comment by CkShibit** [comment]
Traceback (most recent call last):
  File "./pipelines/demo/image_demo.py", line 46, in <module>
    main()
  File "./pipelines/demo/image_demo.py", line 40, in main
    get_palette(args.palette),
  File "/root/miniconda3/envs/easyportrait/lib/python3.8/site-packages/mmseg/core/evaluation/class_names.py", line 324, in get_palette
    raise ValueError(f'Unrecognized dataset: {dataset}')
ValueError: Unrecognized dataset: easy_portrait

**Comment by CkShibit** [comment]
python ./pipelines/demo/image_demo.py "/root/workspace/facefusion/input_source/mmexport1705161230807.jpg" "/root/workspace/easyportrait/pipelines/local_configs/easyportrait_experiments_v2/segformer-fp/segformer-fp.py" "/root/workspace/easyportrait/pipelines/models/segformer-fp-512.pth" --palette=easy_portrait --out-file="ttt.png"
/root/miniconda3/envs/easyportrait/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/root/miniconda3/envs/easyportrait/lib/python3.8/site-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: /root/workspace/easyportrait/pipelines/models/segformer-fp-512.pth
Traceback (most recent call last):
  File "./pipelines/demo/image_demo.py", line 46, in <module>
    main()
  File "./pipelines/demo/image_demo.py", line 40, in main
    get_palette(args.palette),
  File "/root/miniconda3/envs/easyportrait/lib/python3.8/site-packages/mmseg/core/evaluation/class_names.py", line 324, in get_palette
    raise ValueError(f'Unrecognized dataset: {dataset}')
ValueError: Unrecognized dataset: easy_portrait
How to soulve the error??

**Comment by hradec** [comment]
try to add the `pipelines` folder to the top of your PYTHONPATH: 
```
export PYTHONPATH=./pipelines/:$PYTHONPATH
```
and run again. 
This depot has a copy of the mmseg module in the `pipelines` folder, where they edited the class_names.py to add the `easy_portrait` palette. 
So you have to force python to load the copy version of mmseg module from the `pipelines` folder, by adding it to the top of PYTHONPATH.

**Comment by Refl-ex** [comment]
> the only thing that helped is to replace [this](https://github.com/hukenovs/easyportrait/blob/4127bdfa56e349df495633e989da2e16edd1ab42/pipelines/mmseg/datasets/pipelines/formatting.py#L281C1-L282C1) line with `img_meta[key] = results.get(key, None)`

You have to manually add padding to test pipelines inside a local config for your own images. This may be because original test/val datasets were preprocessed before to match input shape. It works with additional resize.
```
pipeline=[
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', img_scale=(512, 512), keep_ratio=True),
            dict(type='Pad', size=(512, 512), pad_val=0),
            dict(
                type='Normalize',
                mean=[143.55267075, 132.96705975, 126.94924335],
                std=[60.2625333, 60.32740275, 59.30988645],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
```
