### ISSUE TITLE
Opencv error

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [hukenovs/easyportrait#31]
Any solution to this error?

/usr/local/lib/python3.10/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
load checkpoint from local path: /content/drive/MyDrive/colaboratory/extract_and_aligh_frames/SimSwap/SimSwap_datasets_prepare/Code/mmsegmentation/trained_models/segformer-fp-1024.pth
/usr/local/lib/python3.10/dist-packages/mmseg/models/segmentors/base.py:289: UserWarning: show==False and out_file is not specified, only result image will be returned
  warnings.warn('show==False and out_file is not specified, only '
Figure(1500x1000)
Traceback (most recent call last):
  File "/content/easyportrait/pipelines/./demo/image_demo.py", line 46, in <module>
    main()
  File "/content/easyportrait/pipelines/./demo/image_demo.py", line 36, in main
    show_result_pyplot(
  File "/usr/local/lib/python3.10/dist-packages/mmseg/apis/inference.py", line 145, in show_result_pyplot
    mmcv.imwrite(img, out_file)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/image/io.py", line 319, in imwrite
    flag, img_buff = cv2.imencode(img_ext, img, params)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:1141: error: (-2:Unspecified error) could not find encoder for the specified extension in function 'imencode'

**Comment by Thomas-Ver** [comment]
Have you check the type of your file in the show_result_pyplot() ?
Verify that it's a valid formats for opencv like png,jpg,ppm etc...
