### ISSUE TITLE
ModuleNotFoundError: No module named 'mmseg.registry'

### ISSUE THREAD

**Issue by geocine** [hukenovs/easyportrait#33]
| Specification       | Details                                       |
|---------------------|-----------------------------------------------|
| **OS Name**         | Microsoft Windows 10 Pro                      |
| **Version**         | 10.0.19042 Build 19042                        |
| **Commit**          | ea7025b                                       |
| **Python**          | 3.10.14                                       |
| **CUDA Version**    | 11.6, V11.6.55                                |
| **CUDA Build**      | cuda_11.6.r11.6/compiler.30794723_0           |

```
Traceback (most recent call last):
  File "E:\AIML\easyportrait2\pipelines\demo\image_demo.py", line 6, in <module>
    from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
  File "e:\aiml\easyportrait2\pipelines\mmseg\apis\__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "e:\aiml\easyportrait2\pipelines\mmseg\apis\inference.py", line 8, in <module>
    from mmseg.datasets.pipelines import Compose
  File "e:\aiml\easyportrait2\pipelines\mmseg\datasets\__init__.py", line 24, in <module>
    from .easy_portrait import EasyPortraitDataset
  File "e:\aiml\easyportrait2\pipelines\mmseg\datasets\easy_portrait.py", line 1, in <module>
    from mmseg.registry import DATASETS
ModuleNotFoundError: No module named 'mmseg.registry'
```

I am trying to run with this command:

```
python ./pipelines/demo/image_demo.py ./images/data.jpg ./pipelines/local_configs/easyportrait_experiments_v2/fpn-fp/fpn-fp.py ./fpn-fp-1024.pth --palette=easy_portrait --out-file=out.png
```

**Comment by geocine** [comment]
I am not interested anymore
